sudo: required
language: node
node_js:
  - "12.6"
notifications:
  slack:
    rooms:
      - carprk:GwNndSzXdf0hncxr2I5cwwsn#builds
      - carprk:GwNndSzXdf0hncxr2I5cwwsn#website
    on_success: always
    on_cancel: always
    on_failure: always
    on_start: always
    on_error: always
    on_pull_requests: true
services:
  - docker
install:
  - pip install --user awscli
script:
  - yarn test
after_script:
  - bash .travis-deploy/docker.sh
  - bash .travis-deploy/cloud.sh
  - bash .travis-deploy/data.sh
